version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - es-net
    restart: unless-stopped
  web:
    build: ./3i-analytics
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - elasticsearch
    links:
      - mongo
    networks:
      - es-net
    restart: unless-stopped
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - es-net
    restart: unless-stopped
  mqtt:
    build: ./mqtt-es-middleware
    networks:
      - es-net
    depends_on:
      - web
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    networks:
      - es-net
    volumes:
      - ./mosquitto:/mosquitto/config
    restart: unless-stopped
networks:
  es-net:
    driver: bridge
